/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-05-10 19:39:48 UTC)
 * on 2013-05-11 at 23:08:51 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.models.model;

/**
 * Model definition for Tracks.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-api-java-client/wiki/Json">http://code.google.com/p/google-api-java-client/wiki/Json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Tracks extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Track> track;

  static {
    // hack to force ProGuard to consider Track used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(Track.class);
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Track> getTrack() {
    return track;
  }

  /**
   * @param track track or {@code null} for none
   */
  public Tracks setTrack(java.util.List<Track> track) {
    this.track = track;
    return this;
  }

  @Override
  public Tracks set(String fieldName, Object value) {
    return (Tracks) super.set(fieldName, value);
  }

  @Override
  public Tracks clone() {
    return (Tracks) super.clone();
  }

}
