/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-05-10 19:39:48 UTC)
 * on 2013-05-11 at 23:08:51 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.models;

/**
 * Service definition for Models (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ModelsRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Models extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION == 14,
        "You are currently running with version %s of google-api-client. " +
        "You need version 1.14 of google-api-client to run version " +
        "1.14.2-beta of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://dcontwenty.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "models/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Models(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Models(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "searchsuggest".
   *
   * This request holds the parameters needed by the the models server.  After setting any optional
   * parameters, call the {@link Searchsuggest#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public Searchsuggest searchsuggest() throws java.io.IOException {
    Searchsuggest result = new Searchsuggest();
    initialize(result);
    return result;
  }

  public class Searchsuggest extends ModelsRequest<com.google.api.services.models.model.SearchSuggestions> {

    private static final String REST_PATH = "searchsuggest/get";

    /**
     * Create a request for the method "searchsuggest".
     *
     * This request holds the parameters needed by the the models server.  After setting any optional
     * parameters, call the {@link Searchsuggest#execute()} method to invoke the remote operation. <p>
     * {@link Searchsuggest#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientR
     * equest)} must be called to initialize this instance immediately after invoking the constructor.
     * </p>
     *
     * @since 1.13
     */
    protected Searchsuggest() {
      super(Models.this, "GET", REST_PATH, null, com.google.api.services.models.model.SearchSuggestions.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public Searchsuggest setAlt(java.lang.String alt) {
      return (Searchsuggest) super.setAlt(alt);
    }

    @Override
    public Searchsuggest setFields(java.lang.String fields) {
      return (Searchsuggest) super.setFields(fields);
    }

    @Override
    public Searchsuggest setKey(java.lang.String key) {
      return (Searchsuggest) super.setKey(key);
    }

    @Override
    public Searchsuggest setOauthToken(java.lang.String oauthToken) {
      return (Searchsuggest) super.setOauthToken(oauthToken);
    }

    @Override
    public Searchsuggest setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Searchsuggest) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Searchsuggest setQuotaUser(java.lang.String quotaUser) {
      return (Searchsuggest) super.setQuotaUser(quotaUser);
    }

    @Override
    public Searchsuggest setUserIp(java.lang.String userIp) {
      return (Searchsuggest) super.setUserIp(userIp);
    }

    @Override
    public Searchsuggest set(String parameterName, Object value) {
      return (Searchsuggest) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "tracks".
   *
   * This request holds the parameters needed by the the models server.  After setting any optional
   * parameters, call the {@link Tracks#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public Tracks tracks() throws java.io.IOException {
    Tracks result = new Tracks();
    initialize(result);
    return result;
  }

  public class Tracks extends ModelsRequest<com.google.api.services.models.model.Tracks> {

    private static final String REST_PATH = "tracks/get";

    /**
     * Create a request for the method "tracks".
     *
     * This request holds the parameters needed by the the models server.  After setting any optional
     * parameters, call the {@link Tracks#execute()} method to invoke the remote operation. <p> {@link
     * Tracks#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected Tracks() {
      super(Models.this, "GET", REST_PATH, null, com.google.api.services.models.model.Tracks.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public Tracks setAlt(java.lang.String alt) {
      return (Tracks) super.setAlt(alt);
    }

    @Override
    public Tracks setFields(java.lang.String fields) {
      return (Tracks) super.setFields(fields);
    }

    @Override
    public Tracks setKey(java.lang.String key) {
      return (Tracks) super.setKey(key);
    }

    @Override
    public Tracks setOauthToken(java.lang.String oauthToken) {
      return (Tracks) super.setOauthToken(oauthToken);
    }

    @Override
    public Tracks setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Tracks) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Tracks setQuotaUser(java.lang.String quotaUser) {
      return (Tracks) super.setQuotaUser(quotaUser);
    }

    @Override
    public Tracks setUserIp(java.lang.String userIp) {
      return (Tracks) super.setUserIp(userIp);
    }

    @Override
    public Tracks set(String parameterName, Object value) {
      return (Tracks) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Models}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Models}. */
    @Override
    public Models build() {
      return new Models(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ModelsRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setModelsRequestInitializer(
        ModelsRequestInitializer modelsRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(modelsRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
